apiVersion: v1
kind: Service
metadata:
  name: testlink
  labels:
    app: testlink
  namespace: testlink
spec:
  type: LoadBalancer
  selector:
    app: testlink
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
